[package]
name = "pyshop_hasher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.1", features = ["derive"] }
num_cpus = "1.16.0"
sha256 = "1.4.0" 
threadpool = "1.8.1"